version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: 'sunday'
      time: '21:00'
      timezone: 'Asia/Tokyo'
    allow:
      - dependency-type: 'development'
    commit-message:
      prefix: '[npm]'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    target-branch: 'develop'
    labels:
      - 'dependabot'
      - 'npm'
      - 'dependencies'
    versioning-strategy: 'increase-if-necessary'
