name: Lighthouse CI

on:
  pull_request:
    branches:
      - main

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: pnpm install
        run: |
          pnpm install
      - name: run Lighthouse CI
        run: |
          pnpm install -g @lhci/cli@0.11.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
